name: 密钥扫描

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 加固运行器（审计所有出站调用）
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit
    - name: 检出代码
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: 密钥扫描
      uses: trufflesecurity/trufflehog@bcfcf73aaf4759d4dadc2783177c245a02792318 # main
      with:
        extra_args: --results=verified,unknown
